server:
  port: 8080

# logging:
#   level:
#     liquibase: DEBUG
invoice.storage.path=invoices/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vivek
    username: postgres
    password: Vivek
    driver-class-name: org.postgresql.Driver
    
  web:
    resources:
      static-locations: file:invoices/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
server:
  error:
    whitelabel:
      enabled: false
