server:
  port: ${PORT:8080}   # Use Render's assigned port or 8080 locally
  error:
    whitelabel:
      enabled: false   # Disable default white-label error page

invoice:
  storage:
    path: invoices/    # Folder for storing generated PDF invoices

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vivek
    username: postgres
    password: Vivek
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  web:
    resources:
      static-locations: file:invoices/

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
