server:
  port: 9199

# Optional logging
# logging:
#   level:
#     liquibase: DEBUG

invoice:
  storage:
    path: C:/Java_coder_workspace/InvicePdfApplication/invoices/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vivek
    username: postgres
    password: Vivek
    driver-class-name: org.postgresql.Driver

  web:
    resources:
      # âœ… This lets you serve files directly from "invoices" via http://localhost:9199/invoices/
      static-locations: file:C:/Java_coder_workspace/InvicePdfApplication/invoices/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
